export const art_titles = [
    "North Woods Reflection",
    "Shohola Falls 1",
    "Shohola Falls 2",
    "Lone Oak Trailhead NH",
    "North Woods Creek",
    "Waldeinsamkeit",
    "Orchard",
    "Saint Francis",
    "Twig",
    "Polar Caves NH",
    "Wave Columns",
    "Battery",
    "Object",
    "Blinky",
    "Toast",
    "Folding Panel 3",
    "Folding Panel 2",
    "Enterprise Panel",
    "Folding Panel",
    "Wave Panel",
];
