export const artData = [
  {
    title: "North Woods Reflection",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084165/compressed%20portfolio/north_woods_reflection_zi74tr.jpg",
    dimensions: "18x24 in",
    material: "Oil on Panel",
  },
  {
    title: "Shohola Falls 1",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084172/compressed%20portfolio/shohola_falls_1_vgayhv.jpg",
    dimensions: "18x24 in",
    material: "Oil on Panel",
  },
  {
    title: "Shohola Falls 2",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084168/compressed%20portfolio/shohola_falls_pm68an.jpg",
    dimensions: "18x24 in",
    material: "Oil on Panel",
  },
  {
    title: "Lone Oak Trailhead NH",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084167/compressed%20portfolio/romans_nose_c6mlwo.jpg",
    dimensions: "18x24 in",
    material: "Oil on Panel",
  },
  {
    title: "North Woods Creek",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084164/compressed%20portfolio/north_woods_creek_fngrbc.jpg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "Waldeinsamkeit",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084170/compressed%20portfolio/waldeinsamkeit_s8lx8s.jpg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "Orchard",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084166/compressed%20portfolio/great_lawn_wlksuk.jpg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "North Woods Tree",
    src: "north_woods_tree.jpeg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "Saint Francis",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084171/compressed%20portfolio/saint_francis_dne6jx.jpg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "Twig",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084172/compressed%20portfolio/north_woods_twiggy_i7d0v6.jpg",
    dimensions: "8x10 in",
    material: "Oil on Pnael",
  },
  {
    title: "Polar Caves NH",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084168/compressed%20portfolio/polar_caves_nh_oidjvp.jpg",
    dimensions: "24x30 in",
    material: "Oil on Panel",
  },
  {
    title: "Wave Columns",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084170/compressed%20portfolio/wave_columns_nkqfh6.jpg",
    dimensions: "9x12 in",
    material: "Laminate, Plywood, Lacquer",
  },
  {
    title: "Into Thick Air",
    src: "into_thick_air.jpeg",
    dimensions: "12x16 in",
    material: "Plywood, Matte Medium",
  },
  {
    title: "Battery",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084164/compressed%20portfolio/battery_k2x6px.jpg",
    dimensions: "9x12 in",
    material: "Laminate, Plywood, Ash, Lacquer",
  },
  {
    title: "Object",
    src: "https://res.cloudinary.com/doadukwfh/image/upload/v1703084166/compressed%20portfolio/object_8_cdywim.jpg",
    dimensions: "8x10 in",
    material: "Laminate, Plywood, Oak, Lacquer",
  },
  {
    title: "Blinky",
    src: "blinky.jpeg",
    dimensions: "22x28 in",
    material: "Laminate, Plywood, Oak, Lacquer",
  },
  {
    title: "Folding Panel 3",
    src: "foldpanel.JPG",
    dimensions: "30x40 in",
    material: "Laminate, Plywood, Lacquer",
  },
  {
    title: "Folding Panel 2",
    src: "niceeaster.JPG",
    dimensions: "12x13 in",
    material: "Laminate, Plywood, Lacquer",
  },
  {
    title: "Enterprise Panel",
    src: "enterprize.JPG",
    dimensions: "14x13 in",
    material: "Laminate, Plywood, Lacquer, Cardboard",
  },
  {
    title: "Folding Panel",
    src: "tallfoldy.JPG",
    dimensions: "9x14 in",
    material: "Laminate, Plywood, Lacquer",
  },
  {
    title: "Wave Panel",
    src: "wavy.JPG",
    dimensions: "7x10 in",
    material: "Laminate, Plywood, Lacquer, Oak",
  },
  {
    title: "Toast",
    src: "toast.JPG",
    dimensions: "7x10 in",
    material: "Laminate, Plywood, Lacquer, Oak",
  },
];
